<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ActionButton_Ubah</name>
   <tag></tag>
   <elementGuidId>49acc46e-796b-421e-88f6-e30b2d6229cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(.,'Ubah')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-group.open > ul.dropdown-menu.pull-right > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea6c5afa-e5b6-48b8-8dbb-154ad48fd4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>883bccb2-f86d-45d7-a037-659ad746ba53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RowHeaderEdit(1);</value>
      <webElementGuid>95aed6c0-0985-4413-bb6c-bb1044ac4c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah </value>
      <webElementGuid>17cf2c82-74b8-4044-955c-1c7d34881b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/td[@class=&quot;colActInGrid&quot;]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu pull-right&quot;]/li[1]/a[1]</value>
      <webElementGuid>827bb0b6-84be-412c-96bd-905f74608c5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='RowHeaderEdit(1);']</value>
      <webElementGuid>ea1743f1-b4ba-4e1f-850c-3391da1d6649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[11]/div/ul/li/a</value>
      <webElementGuid>aebf4096-2bba-421c-8ec0-fd0b834f4067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ubah')]</value>
      <webElementGuid>6d99b284-27e4-478b-9a96-7ed5c454a9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permintaan Baru'])[2]/following::a[1]</value>
      <webElementGuid>411fb082-d38c-46f9-9a8a-49ebab2f56cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPK Utama'])[2]/following::a[1]</value>
      <webElementGuid>e6ccfc25-4345-4f42-87fd-3bc54b043a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Data'])[1]/preceding::a[1]</value>
      <webElementGuid>3f92912d-7cdc-46e2-8746-95e9103f928a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simon, S.Kom'])[1]/preceding::a[2]</value>
      <webElementGuid>18dedc53-ec54-4975-98d5-d0ab936d3061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>3279637b-664d-40df-843f-99fe23ef54f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[11]</value>
      <webElementGuid>bd738e5f-88d2-4094-be3c-05e1b443453a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/ul/li/a</value>
      <webElementGuid>adb54034-a89f-4b57-b420-9188636f79ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Ubah ' or . = 'Ubah ')]</value>
      <webElementGuid>a10aa4b3-28c0-4fce-b87f-1340ea3c4ca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
