<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_btn_Menyetujui</name>
   <tag></tag>
   <elementGuidId>18b32737-6a5f-4c7a-a131-3c61b4a6a479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='APV_mod_Approve']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#APV_mod_Approve</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc004d4b-bdf2-401d-8648-a78bd4d6b8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>APV_mod_Approve</value>
      <webElementGuid>a55bf414-b354-4e96-8f07-6ed421d6586f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>bbdff635-5b75-4821-9806-0b744c3c7233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>48cdb50d-fbdb-4382-aa4f-2f27db0f2892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menyetujui</value>
      <webElementGuid>f83a9040-84f8-48e4-83ac-e9ab90feb4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;APV_mod_Approve&quot;)</value>
      <webElementGuid>fa0a018b-b65a-4806-8ef5-8bdac435ff3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='APV_mod_Approve']</value>
      <webElementGuid>9edd54fc-b6b5-43c3-bd5a-e23c4c32b14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='APV_Modal_Edit']/div/div/div[3]/button[3]</value>
      <webElementGuid>7a331de1-92d9-4920-b306-3b2bb5c8fcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menolak'])[1]/following::button[1]</value>
      <webElementGuid>dddff53b-1ff3-41cb-bb9d-f906c3187e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menyetujui']/parent::*</value>
      <webElementGuid>c60a1f36-d10b-4563-9429-a913a9b77596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[3]</value>
      <webElementGuid>178c807d-7232-4a58-a636-0da03dbd9b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'APV_mod_Approve' and (text() = 'Menyetujui' or . = 'Menyetujui')]</value>
      <webElementGuid>0ea07e5e-02ef-439c-9753-6e39b10c9241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
