<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserAccount</name>
   <tag></tag>
   <elementGuidId>f4dc1253-7c36-44a4-a920-75c6f251ffaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-navbar-collapse']/div/div/ul/li[5]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-toggle.user-menu > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4112a40-eca1-43a7-88e3-fcc88bd71d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Officer (Trial)</value>
      <webElementGuid>29d250f5-a018-427a-a1e2-013b86ce7ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-navbar-collapse&quot;)/div[1]/div[@class=&quot;right clearfix&quot;]/ul[@class=&quot;nav navbar-nav pull-right right-navbar-nav&quot;]/li[@class=&quot;dropdown&quot;]/a[@class=&quot;dropdown-toggle user-menu&quot;]/span[1]</value>
      <webElementGuid>dae3f7bb-6bd7-47a7-85b9-e3a9402d9a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-navbar-collapse']/div/div/ul/li[5]/a/span</value>
      <webElementGuid>747a7c7a-9042-48de-8a30-a9e116b752c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoming messages'])[1]/following::span[1]</value>
      <webElementGuid>731bdb4f-7cfb-4468-a150-09b65d654c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/preceding::span[1]</value>
      <webElementGuid>4d7bbda9-74b6-4443-bbaf-27ebb75facef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Officer (Trial)']/parent::*</value>
      <webElementGuid>4958d189-a8c9-44a0-ac73-f6ee25fcb9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>4c0632c2-bdd1-4d7d-871f-8cd06dfa2006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Officer (Trial)' or . = 'Officer (Trial)')]</value>
      <webElementGuid>e6a139dc-cc5b-42c5-9d5b-fbf1af67edc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
