<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DDL_No_SPK</name>
   <tag></tag>
   <elementGuidId>b4e8bff3-d8f0-4308-8e23-62b689d4af78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s2id_ddlSPKRef > a.select2-choice > span.select2-chosen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s2id_ddlSPKRef']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>782af16e-9ff3-4aec-9ebb-29f6140f0fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-chosen</value>
      <webElementGuid>3a92c6bd-3a38-47df-b95b-42c8ceaab436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--  Pilih Kode SPK  --</value>
      <webElementGuid>73a9fc29-3f34-4f0e-afa5-85079e4a91a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s2id_ddlSPKRef&quot;)/a[@class=&quot;select2-choice&quot;]/span[@class=&quot;select2-chosen&quot;]</value>
      <webElementGuid>79fc93ce-05ac-4a08-8e39-fe55c3c9b79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s2id_ddlSPKRef']/a/span</value>
      <webElementGuid>84b815a5-85f4-49d8-a525-efafae77ca64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No SPK Utama'])[1]/following::span[1]</value>
      <webElementGuid>541c1520-720f-4198-8479-280fad5a344a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Pilih --'])[2]/following::span[2]</value>
      <webElementGuid>25f658fe-a096-4df6-b053-4b8fa085e9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal SPK'])[2]/preceding::span[2]</value>
      <webElementGuid>e9ac2fcb-7b1a-42cb-bbc7-7c1bdcce2754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/div/div/a/span</value>
      <webElementGuid>19237cef-7bdc-4358-b734-2a34c454a886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '--  Pilih Kode SPK  --' or . = '--  Pilih Kode SPK  --')]</value>
      <webElementGuid>9d7f84ac-9970-4510-b8b3-b663dae7e9e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
