<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_PopUp_PilihSemuaHargaSatuan</name>
   <tag></tag>
   <elementGuidId>583780bf-3bf2-4d9b-a0b1-5f9ffa338b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label > input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='multiselect-all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b77b9ef-588e-49d1-b3f3-f303356578ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a4130b70-7b25-4467-947c-eb4a3416312a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>multiselect-all</value>
      <webElementGuid>00724a80-b52a-46fa-8e71-386832f76ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LantaiGrid&quot;)/tbody[1]/tr[@id=&quot;1&quot;]/td[8]/div[@class=&quot;SubPriceList&quot;]/span[@class=&quot;multiselect-native-select&quot;]/span[@class=&quot;multiselect-native-select&quot;]/span[@class=&quot;multiselect-native-select&quot;]/span[@class=&quot;multiselect-native-select&quot;]/span[@class=&quot;multiselect-native-select&quot;]/span[@class=&quot;multiselect-native-select&quot;]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;multiselect-container dropdown-menu&quot;]/li[@class=&quot;multiselect-item multiselect-all&quot;]/a[@class=&quot;multiselect-all&quot;]/label[1]/input[1]</value>
      <webElementGuid>195514d5-8f9e-46cc-8db2-d150f9266f5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='multiselect-all']</value>
      <webElementGuid>48066386-cd21-4366-9564-547c9711c4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[8]/div/span/span/span/span/span/span/div/ul/li[2]/a/label/input</value>
      <webElementGuid>cd657fe2-6a9b-4ef6-80eb-7f1279f3d758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>9576b520-f6de-47f3-809b-dc9dea88eb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>46179be5-403e-4909-b940-3fea677a925c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
