<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_PopUp_Pilih TLZ</name>
   <tag></tag>
   <elementGuidId>bed3f990-9170-4ea7-9a31-653505d9270d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jqg_LantaiGrid_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jqg_LantaiGrid_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa5cafbd-bcf2-4568-9e59-25e736e714c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3f1f8d62-e150-4d83-9d11-818671712d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>13fde9d2-1a63-40dd-a253-613277b7c564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg_LantaiGrid_1</value>
      <webElementGuid>b3d3982b-a047-410c-b2d7-d9773c8b6b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cbox</value>
      <webElementGuid>dcd07188-f781-4943-96f2-2b41dc45a84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jqg_LantaiGrid_1</value>
      <webElementGuid>b073d485-b2ab-4b2f-9333-935ed88dd910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg_LantaiGrid_1&quot;)</value>
      <webElementGuid>101995de-ae4c-4204-ba74-7c3a41488704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg_LantaiGrid_1']</value>
      <webElementGuid>770780b1-3e8c-4ca9-96ff-f4ff2d5d37a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[2]/input</value>
      <webElementGuid>55b2e442-4ca2-4e74-ac93-b6d22015d4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>0425ef98-e36d-494d-8d2f-7f6507459a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'jqg_LantaiGrid_1' and @name = 'jqg_LantaiGrid_1']</value>
      <webElementGuid>7cf4bb62-8438-473d-82cc-1c1dbc24d451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
