<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_Button_PilihLantai</name>
   <tag></tag>
   <elementGuidId>baa95911-b802-4a4b-aa7d-1601c8b7412a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jqg1_btnViewLantai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='jqg1_btnViewLantai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a99db1fa-d953-4b45-ad8b-cc013f4e7131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline</value>
      <webElementGuid>9f46654a-df1b-44f2-a61f-2746ff93e1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg1_btnViewLantai</value>
      <webElementGuid>f9612c99-b291-424b-ae5e-159d4e604ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenLantai(&quot;jqg1&quot;);</value>
      <webElementGuid>2b617736-3471-46b2-b83c-14b7e3f6acf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Lantai</value>
      <webElementGuid>f1ee705c-2ff1-466c-beec-67d6c2ebbeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg1_btnViewLantai&quot;)</value>
      <webElementGuid>40b3ddf6-516d-425e-95ee-6b228b88a339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='jqg1_btnViewLantai']</value>
      <webElementGuid>6472cd40-d220-4d48-bf4b-3133e5b865ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg1']/td[9]/button</value>
      <webElementGuid>f4810a1f-d796-455b-b064-1bec31852904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area'])[1]/following::button[1]</value>
      <webElementGuid>812c53a7-cd85-4da9-a59b-79a4d70f3ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utama'])[2]/following::button[1]</value>
      <webElementGuid>d7b9e00f-a624-41d2-b3ba-6713b049d043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[6]/preceding::button[2]</value>
      <webElementGuid>b3e010ac-ab93-446a-99df-1b261c47e3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Lantai']/parent::*</value>
      <webElementGuid>5017db01-e075-4f15-95f2-81b09170929c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/button</value>
      <webElementGuid>f1ba5d7c-ec6a-4e20-a35d-ebbf7befaaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'jqg1_btnViewLantai' and (text() = 'Pilih Lantai' or . = 'Pilih Lantai')]</value>
      <webElementGuid>1e8534fa-d131-43ab-aa2e-b46cfa3ef100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
