<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_PopUp_Input_Keterangan</name>
   <tag></tag>
   <elementGuidId>19ac72f6-a133-4c8f-ab3a-d20fb48a2a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1_KeteranganSub</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1_KeteranganSub']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e28f070e-883a-47e7-839d-1fdd175b51d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41d015a2-f7b6-4f48-aaa5-572748127beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_KeteranganSub</value>
      <webElementGuid>df1eb03b-c5d9-46a8-b3da-41230910607c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>KeteranganSub</value>
      <webElementGuid>ae80797c-ab45-452f-b3ff-d0a392f30b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7e2a06f2-d65b-4d0e-a7c0-668249336de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>d34a58c6-5236-4f51-8557-0def5e0324e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_KeteranganSub&quot;)</value>
      <webElementGuid>925c3230-4bff-4ef7-9699-0d147341e185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1_KeteranganSub']</value>
      <webElementGuid>794df530-6453-4f15-80d4-de693f7f7be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[6]/input</value>
      <webElementGuid>eddd0c73-858b-4e75-abde-8e23a335c9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/div[3]/div/table/tbody/tr[2]/td[6]/input</value>
      <webElementGuid>aa0821af-d3e1-4895-b22e-29dee4a8ab96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '1_KeteranganSub' and @name = 'KeteranganSub']</value>
      <webElementGuid>18656e85-c85a-4ea7-accc-00228ed6eaa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
