<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_PopUp_ButtonTambahHargaSatuan</name>
   <tag></tag>
   <elementGuidId>0f1cf1cc-f286-4ed9-ba0d-f358a23473cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1_AddPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='1_AddPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aae2cefd-3829-4b0a-b41b-af473177ad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>209f8936-20e7-43fc-98cb-d11feae7df21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_AddPrice</value>
      <webElementGuid>a7cb4502-0cc0-408d-a4e2-a9dd4a1605c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AddPrice(LantaiGrid, 1);</value>
      <webElementGuid>8add9a68-1c30-45ee-a3b9-4c8efbbdba65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_AddPrice&quot;)</value>
      <webElementGuid>f1b55d2b-5a99-4756-ab9d-2718038776e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='1_AddPrice']</value>
      <webElementGuid>fab13fe4-c8be-4e83-88e9-9fdbb3112908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[8]/div/button</value>
      <webElementGuid>090b67e5-de32-4a97-8c6e-101c05d53a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL'])[1]/following::button[2]</value>
      <webElementGuid>23e9483d-ff65-489d-a5d2-29f7e17b3b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basement 2'])[1]/following::button[2]</value>
      <webElementGuid>5c19258c-c93f-4ffe-bf8c-2ff550433a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area 4'])[2]/preceding::button[1]</value>
      <webElementGuid>2f12c596-bed0-41b6-bd61-18554bf3c314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basement 2'])[2]/preceding::button[1]</value>
      <webElementGuid>149939d0-eb0a-4be4-8aa9-00d40a8001bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/button</value>
      <webElementGuid>17d1ed64-d5e7-408b-b222-76ec319f1e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '1_AddPrice']</value>
      <webElementGuid>e412400e-17bb-4068-b5af-bd6eaf8b3686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
