<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_PopUp_Input_HargaSatuan</name>
   <tag></tag>
   <elementGuidId>366c044e-8adc-4c9b-85ab-a697a2445348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtAddPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtAddPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c37519e6-e6ae-4a62-88f8-0793537f783e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de8d2c1b-aadf-43b9-af5a-329de40d8546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-right</value>
      <webElementGuid>cebff63c-a460-4a51-9c39-932ab3d440a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtAddPrice</value>
      <webElementGuid>8904bd19-0560-413a-bd34-422d8628a85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtAddPrice</value>
      <webElementGuid>d4dd64f6-3c08-4789-b06f-86cc00d0acd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtAddPrice&quot;)</value>
      <webElementGuid>f29244a1-dcff-4599-9972-2c2244974ff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtAddPrice']</value>
      <webElementGuid>23c8ceb0-3896-4948-bbdb-b4f1d4eb690c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalAddPrice']/div/div/div[2]/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>4a95bb19-afda-44bf-92db-5289cb91e223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/input</value>
      <webElementGuid>86c9c28e-d209-4c5f-8804-15841dadfb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtAddPrice' and @name = 'txtAddPrice']</value>
      <webElementGuid>18cf0f33-4cc4-43a5-a82b-323f555ee1bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
