<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_PopUp_Button_Set</name>
   <tag></tag>
   <elementGuidId>ddd8e2c3-5970-4101-8115-4f3eb30454bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>737a626b-ab03-426f-93f7-402117c741ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>513143f8-4390-47bd-ad73-298993249859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSet</value>
      <webElementGuid>8109837b-6e55-4b14-aa45-c505a0c36c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>9943c362-b5ae-44b9-93ac-40e4da53d6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Set</value>
      <webElementGuid>8af3795c-6096-4dad-b4cd-be34f1ca6978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSet&quot;)</value>
      <webElementGuid>a0453a94-54cc-4f35-bcaf-155344c2de1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSet']</value>
      <webElementGuid>58b3e75b-9873-4eee-892b-c76428a3f77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalLantai']/div/div/div[3]/button</value>
      <webElementGuid>36914827-5b57-4858-a58f-7dd178a07661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View 1 - 5 of 181'])[1]/following::button[1]</value>
      <webElementGuid>ef8609b6-c2dc-42fc-915d-82acafdcdc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/preceding::button[2]</value>
      <webElementGuid>9c96cab3-ac5c-4210-9c3e-94651a90a02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaya Penanganan Complain'])[1]/preceding::button[3]</value>
      <webElementGuid>c08dcd9c-e152-4f58-b949-164d7d2a1e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Set']/parent::*</value>
      <webElementGuid>f48222ed-e382-47df-8ef7-9b430ba914f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[3]/button</value>
      <webElementGuid>6eafb4ce-9e51-4b9f-a626-45c0af32fea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSet' and (text() = 'Set' or . = 'Set')]</value>
      <webElementGuid>2b4918c2-2baa-44d1-8d3d-0e01041d0a6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
