<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_PopUp_Button_Simpan HargaSatuan</name>
   <tag></tag>
   <elementGuidId>a7354adc-8e2f-484b-ade3-5bded2bbddc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveAddPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSaveAddPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b66e8037-56b9-44d9-b0e9-094fb93149ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveAddPrice</value>
      <webElementGuid>96c066e8-a380-4a48-9c87-9193adbf8e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green metro-save btn_save</value>
      <webElementGuid>4aa88005-e548-4be4-87a6-afb3ca0d61e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>f60ab6d3-8026-4ea3-a726-b063a7c6062d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>4d503e85-e1fb-4b8b-b038-9b0a3d0e7252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveAddPrice&quot;)</value>
      <webElementGuid>55c2ed9d-9dea-45c5-b186-d3a9e804cb15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSaveAddPrice']</value>
      <webElementGuid>a01772d2-86f5-4cef-aa6a-c59c9405eb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalAddPrice']/div/div/div[3]/button</value>
      <webElementGuid>9f53b948-5e70-4a52-be84-0ede64290fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit'])[2]/following::button[1]</value>
      <webElementGuid>1dc783d6-4466-4ae1-aa11-75715a968061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[2]/following::button[1]</value>
      <webElementGuid>6c02cf14-e680-4f90-916e-5652fc4ffdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[3]/button</value>
      <webElementGuid>3385add8-8dfc-4595-b485-5500317caeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveAddPrice' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>d381edba-4534-45fb-b894-e4c7963eb77e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
