<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Status_Persetujuan</name>
   <tag></tag>
   <elementGuidId>2c4a5549-18c4-44cf-acaa-338442617e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Status_Approval_Str</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gs_Status_Approval_Str']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a08c717d-515b-4ccf-9da0-0796b9c15019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Status_Approval_Str</value>
      <webElementGuid>34d96c9b-9181-413c-91e2-53c2072c7592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Status_Approval_Str</value>
      <webElementGuid>cad266c0-595c-4417-8c66-5d90524d765d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semua Not PostedRequest ApproveWaiting for ApprovalApprovedRejected</value>
      <webElementGuid>2aed4de1-8e3a-4759-9f9b-a485794c873e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Status_Approval_Str&quot;)</value>
      <webElementGuid>b7868531-ae75-4c55-9aab-f92750589446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gs_Status_Approval_Str']</value>
      <webElementGuid>050b264b-8a43-48e6-b5c5-925fc253a081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[10]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>303858e8-c1de-4b90-92fd-be31e08c81d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[8]/following::select[1]</value>
      <webElementGuid>b4433787-f474-4cd0-a13c-93da18e00e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[7]/following::select[2]</value>
      <webElementGuid>6e92cfe7-26a6-4755-bc78-fdbe93d4c777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[9]/preceding::select[1]</value>
      <webElementGuid>1353fc17-49d3-42a2-87a7-dd68888d9aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[10]/preceding::select[1]</value>
      <webElementGuid>9aa1d2c9-46cd-4a9c-b33b-5448bb518793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[10]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>640bbd73-4b66-4948-9c25-22ef9184dc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Status_Approval_Str' and @id = 'gs_Status_Approval_Str' and (text() = 'Semua Not PostedRequest ApproveWaiting for ApprovalApprovedRejected' or . = 'Semua Not PostedRequest ApproveWaiting for ApprovalApprovedRejected')]</value>
      <webElementGuid>25e2690b-8490-4c9f-b600-bd1e0bcecec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
