<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Status</name>
   <tag></tag>
   <elementGuidId>066c68a9-dff2-45f5-b95a-691662ae4ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gs_Status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bcd4b080-e8f9-48ac-9dc3-b94be9daa336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>324744c9-e94c-4110-9123-e70f2f979203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Status</value>
      <webElementGuid>f63f4a23-600f-47ee-882f-5c5048c9bdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semua AktifPermintaan BaruDibatalkan</value>
      <webElementGuid>9f8ad869-e372-4513-94a4-2451946b77fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Status&quot;)</value>
      <webElementGuid>009afb61-99b6-4176-82d2-9a9a271a234f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gs_Status']</value>
      <webElementGuid>0772ba59-7765-4a1b-9ba0-1ee4f7b3f44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[9]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>4f181d5e-7a1a-470c-a68f-29b0e715434a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[7]/following::select[1]</value>
      <webElementGuid>4cb35fe9-0393-4a98-a2ec-811db73fec83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[6]/following::select[1]</value>
      <webElementGuid>683a51ad-a8b5-4a6c-b65c-f16eaa3c08b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[8]/preceding::select[1]</value>
      <webElementGuid>2896a0ba-5bbc-4341-92fd-370728124687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[9]/preceding::select[2]</value>
      <webElementGuid>dd7f89b1-f77b-4824-840c-39fc9c0c117b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[9]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>1e9607dd-b795-4260-a020-59e5e34d3790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Status' and @id = 'gs_Status' and (text() = 'Semua AktifPermintaan BaruDibatalkan' or . = 'Semua AktifPermintaan BaruDibatalkan')]</value>
      <webElementGuid>69d7987e-3f9e-4113-b47f-d8d28f6863d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
