<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_Jenis_SPK</name>
   <tag></tag>
   <elementGuidId>164001b8-e788-4afe-9877-5f57d06014c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Deskripsi_Jenis_SPK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gs_Deskripsi_Jenis_SPK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a647b6ea-2200-4328-b865-94235b0109b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Deskripsi_Jenis_SPK</value>
      <webElementGuid>bd7a1fcb-34e1-4361-be3d-ad895ca92a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Deskripsi_Jenis_SPK</value>
      <webElementGuid>1568a6af-c01d-46e4-aa01-dd2be5e17010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Semua SPK UtamaSPK Tambahan KTK </value>
      <webElementGuid>1b7c1391-a768-4d31-83d9-34ac1742786d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Deskripsi_Jenis_SPK&quot;)</value>
      <webElementGuid>a5e98f49-db2a-40a5-9057-d7a9d1c81b8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gs_Deskripsi_Jenis_SPK']</value>
      <webElementGuid>c8db3cf2-55e2-4672-bc3b-2dedfb5db275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[5]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>7ea3ac2f-dfee-4229-950a-09340a39061a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[3]/following::select[1]</value>
      <webElementGuid>5e1b7517-9923-451f-94c9-03dea57624e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[2]/following::select[1]</value>
      <webElementGuid>b5698fba-8c29-44c7-9f99-ce4ac108b34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[4]/preceding::select[1]</value>
      <webElementGuid>877b86fe-9900-4c5e-a863-854d82e0c038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[5]/preceding::select[1]</value>
      <webElementGuid>be589b9b-e827-4be8-939e-2e0238c956f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>886ca5b5-bb3b-4f7d-b82c-33c0f0632324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Deskripsi_Jenis_SPK' and @id = 'gs_Deskripsi_Jenis_SPK' and (text() = ' Semua SPK UtamaSPK Tambahan KTK ' or . = ' Semua SPK UtamaSPK Tambahan KTK ')]</value>
      <webElementGuid>3e854fe3-ebb5-4acf-a206-26c3ebfc3a3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
