<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Tanggal_SPK</name>
   <tag></tag>
   <elementGuidId>36933b8c-9c55-48cc-87ab-b0075e52e1a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Tanggal_SPK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Tanggal_SPK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>123aaa0b-1958-4920-a7b8-fa29f9917b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e1aca75-dae0-4889-bb4d-e980cef5a1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Tanggal_SPK</value>
      <webElementGuid>5433105e-cc51-45ac-8186-96d0e41ae891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Tanggal_SPK</value>
      <webElementGuid>928b2e83-dda0-4620-b8a2-3f57bdd1c252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Tanggal_SPK&quot;)</value>
      <webElementGuid>cc0fa99f-ee3d-4dce-b03c-6cfe04d006d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Tanggal_SPK']</value>
      <webElementGuid>3e5010f1-e4e9-4632-a66d-d2b7c4dc534e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[6]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>4d73acb4-f981-4a42-97b7-53d160389a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f87bdb34-7f3c-415e-b580-b374af806936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Tanggal_SPK' and @id = 'gs_Tanggal_SPK']</value>
      <webElementGuid>85e01364-211c-4bd1-95d3-4b9379a1adb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
