<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Nama_Vendor</name>
   <tag></tag>
   <elementGuidId>9abce725-f1ba-42c7-aa1a-be46de26c176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Nama_Vendor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Nama_Vendor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90ce6f8f-d30a-48cd-b59c-f3cd968826ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63039154-116a-4591-b720-f737f97791fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nama_Vendor</value>
      <webElementGuid>4d704db0-419f-4306-8b9d-b859e23198b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Nama_Vendor</value>
      <webElementGuid>565797fd-3d7d-4095-a909-99704e32f142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Nama_Vendor&quot;)</value>
      <webElementGuid>0ee6de0d-8c46-4ee7-88ad-dc5894e4dab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Nama_Vendor']</value>
      <webElementGuid>36d91415-58fc-4ab3-af1c-a5c2b5ebc160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>20a9430d-e99a-4f07-a9c6-ab91689a3dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>b16ca4c5-780f-45fc-a05f-3857b3c61c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Nama_Vendor' and @id = 'gs_Nama_Vendor']</value>
      <webElementGuid>a12d6b19-b414-4745-884a-354d54c865d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
