<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Kode_SPK</name>
   <tag></tag>
   <elementGuidId>ab78fda5-024c-4846-b59f-0b3731e0ebe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Kode_SPK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Kode_SPK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1f687be-1c03-497c-926c-f2e024463e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d00fde9-c32b-4df2-938c-dfe2032963ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kode_SPK</value>
      <webElementGuid>5689fc42-e9a4-4993-a698-09ea9f21feeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Kode_SPK</value>
      <webElementGuid>79aaf55e-5b4c-4f15-85c0-2a10875801b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Kode_SPK&quot;)</value>
      <webElementGuid>513ce9ce-fcc9-4202-b30f-ea1f8327e944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Kode_SPK']</value>
      <webElementGuid>781ea9fa-4a94-4243-929d-97ff0992999f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>6149bd1c-ce28-4f47-87bd-eba2e0c12223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>dc1086ec-f478-455e-bde9-90b9f631aa95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Kode_SPK' and @id = 'gs_Kode_SPK']</value>
      <webElementGuid>2b351c64-202a-4cd6-9dc4-c0cdc86b0c65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
