<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_MasaSPK</name>
   <tag></tag>
   <elementGuidId>ae9e2420-24e2-41b4-88c3-c0d2342327a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_MasaSPK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_MasaSPK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b2090ab-0504-4d8b-9195-4f26efb01444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e200c30-e0fd-4c18-85a7-1ca59be022c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MasaSPK</value>
      <webElementGuid>aa46c8dc-76e8-4171-9519-720b34c72971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_MasaSPK</value>
      <webElementGuid>ac26797d-ba8f-4ff9-8775-ec18775fbb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_MasaSPK&quot;)</value>
      <webElementGuid>40ec2a99-c8b6-4918-8c5f-fb294997d2dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_MasaSPK']</value>
      <webElementGuid>3f961463-8adf-4c5f-98ad-227106b09c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[7]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>bb4cd61f-9919-4bf0-8145-48f0af703e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>06fb9056-02d1-4120-873b-a6b2d0c7b2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'MasaSPK' and @id = 'gs_MasaSPK']</value>
      <webElementGuid>293213f6-ab55-460a-b7ad-8eaaf7079cfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
