<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Persentage</name>
   <tag></tag>
   <elementGuidId>8bc3ea5c-a832-49b7-8a72-368600809093</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Persentage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Persentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7412dd5e-af90-42cb-828d-a8f38ad9af86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70292a54-1307-4297-83ff-53fff937bbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Persentage</value>
      <webElementGuid>1da77875-5c77-4756-aff2-607913581b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Persentage</value>
      <webElementGuid>1c815c73-a673-4a8c-95da-e3655fc91597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Persentage&quot;)</value>
      <webElementGuid>34ee6167-080a-4396-950b-243fe127225a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Persentage']</value>
      <webElementGuid>44c496a8-7224-48d5-934c-f2409e1b8591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[8]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>8f7cd838-1f8a-41e8-bffb-5a22533e4896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>97a01ba5-7b74-4cc7-8a50-0eec4e3aae51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Persentage' and @id = 'gs_Persentage']</value>
      <webElementGuid>7fc6e026-6c5e-430c-a5b3-dd6c019ef5da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
