<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tglSelesaiSPK</name>
   <tag></tag>
   <elementGuidId>db1ce905-f2e2-4509-9749-abc7af91715e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tglSelesai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tglSelesai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66251efa-3f7c-443c-b618-ecdf913dabe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f630b79-a8c7-4593-88a8-e96192a3d8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e8b1ca28-c2e9-4a65-b3c6-628983ba8df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tglSelesai</value>
      <webElementGuid>5bf67c26-9720-4d37-8105-b04991e5bd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tglSelesai</value>
      <webElementGuid>0b5800de-6f7b-4023-9ab5-cce8f700af66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tglSelesai&quot;)</value>
      <webElementGuid>6ffc0fe5-831f-408d-85fe-8b390f250eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tglSelesai']</value>
      <webElementGuid>02334c79-08d5-47be-8a98-d8d4af7590a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div[8]/div[2]/div[3]/div/input</value>
      <webElementGuid>d8e1a709-9fa9-4ed6-acaf-e02f6a8e49b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>e6e2e816-120a-405b-8325-a975171acc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tglSelesai' and @name = 'tglSelesai']</value>
      <webElementGuid>069392ec-0a9d-4da5-84ae-1bc9bb5f325b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
