<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tglMulaiSPK</name>
   <tag></tag>
   <elementGuidId>641b1142-9935-4bed-9258-3ed24a07de55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tglMulai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tglMulai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d12b812-dc63-432f-a11f-96e70124f76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fae543a-1dfd-46df-82a4-4879cd9249fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f426d858-a0d9-4d2e-90d8-d015d958b12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tglMulai</value>
      <webElementGuid>36769c77-e938-400c-b2e8-f870761a05f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tglMulai</value>
      <webElementGuid>a95607f2-0dea-4b6b-9096-7a61b88ec73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tglMulai&quot;)</value>
      <webElementGuid>b7e6bb4a-84cc-49af-a024-58ff7fccb751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tglMulai']</value>
      <webElementGuid>af24de30-481f-424d-ad7f-8a40d8f465ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div[8]/div[2]/div/div/input</value>
      <webElementGuid>07df1540-fb41-4b7b-9a4b-6847f969c3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/input</value>
      <webElementGuid>bc0a0faa-5501-48c0-8a2e-8f83bf82bf5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tglMulai' and @name = 'tglMulai']</value>
      <webElementGuid>fab31c15-2c93-4ad2-a549-1f75de6a8215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
