<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_KeteranganSPK</name>
   <tag></tag>
   <elementGuidId>ff7aab8c-30f7-4862-a4ec-af5d751959f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtKeterangan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtKeterangan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aaeb81dd-71e3-48f1-af20-d9e4bf3b1188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtKeterangan</value>
      <webElementGuid>8b116b7f-5bbb-40f2-97d3-79520a89862a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>71008500-9c38-425a-a243-25c6668dad73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>de5cfb0b-9eb3-4073-9dd6-04b749b7ea35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Keterangan</value>
      <webElementGuid>f8fe5ff8-ad58-403e-b127-0cb222873231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtKeterangan&quot;)</value>
      <webElementGuid>8d60157e-7966-4a35-b5a4-d6275f1a0e9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtKeterangan']</value>
      <webElementGuid>9f428b00-d0b8-491d-ac2c-931370e9d7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div[2]/div[4]/div/textarea</value>
      <webElementGuid>2b272c2f-c27f-475a-81b8-6ca2be01456b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2add5b77-fd62-47f9-9001-6d7fd3dcdbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtKeterangan' and @placeholder = 'Masukkan Keterangan']</value>
      <webElementGuid>71921859-f708-407a-a914-6f790a81fead</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
