<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal SPK</name>
   <tag></tag>
   <elementGuidId>e629de0b-f254-4fbf-b426-b063312ebab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tglSPK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tglSPK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d7cc4e5-c207-486e-9a67-bd0ec87ca983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91dbab16-0cb8-4afc-ad81-79b0652db7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>80a07547-83aa-4623-a481-171064a0002c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tglSPK</value>
      <webElementGuid>14473f97-efdc-412c-b077-8d697d1a8d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tglSPK</value>
      <webElementGuid>858d689f-29f3-4674-8b25-6f6dc2010453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tglSPK&quot;)</value>
      <webElementGuid>e79e52fa-ab16-4a70-9bcf-2eb38b3d5e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tglSPK']</value>
      <webElementGuid>82d01a2d-bba1-417d-bd8a-86cbc3a89075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div[7]/div/div/input</value>
      <webElementGuid>b0cb9c03-a9fb-4c89-ba20-0f723533530e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>ec0bdd30-c86c-4fa2-9ab8-ea67535adf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tglSPK' and @name = 'tglSPK']</value>
      <webElementGuid>3da60b6b-42b5-4a47-b2f6-15371e6321a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
