<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ActionButton_Ubah</name>
   <tag></tag>
   <elementGuidId>bb978def-a159-47bd-a54a-098be5d65c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.gridEdit > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='RowHeaderEdit(1);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5af17ff7-9f33-458c-87c6-bc5b1c45e2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>06384e74-52e2-43eb-a104-d3922413d26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RowHeaderEdit(1);</value>
      <webElementGuid>224080a0-c42f-4862-87d2-24371ebe1910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah </value>
      <webElementGuid>ddaf7dca-fdce-4014-968c-dad90a2a8089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/td[@class=&quot;colActInGrid&quot;]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu pull-right&quot;]/li[@class=&quot;gridEdit&quot;]/a[1]</value>
      <webElementGuid>036339e4-2977-41c6-b684-3d9b524da6ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='RowHeaderEdit(1);']</value>
      <webElementGuid>cba50cec-82e5-4c6f-80c8-ab8a00bb4867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[11]/div/ul/li/a</value>
      <webElementGuid>f5f0a941-02dc-4ba9-8348-3227bb4e5507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ubah')]</value>
      <webElementGuid>3e73c049-a20e-44a4-a21d-63aae63dd523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[2]/following::a[1]</value>
      <webElementGuid>5db9e3f3-ac7d-4357-b67f-48bbad41994e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Posted'])[2]/following::a[1]</value>
      <webElementGuid>1a2b1b32-c5bd-4b5b-ad58-dbe6016832b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Data'])[1]/preceding::a[1]</value>
      <webElementGuid>4babdbd2-8cbf-4f1a-847b-3aab9a219825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yokoshita Dwi Purnomo, S.Kom.'])[2]/preceding::a[2]</value>
      <webElementGuid>7bbd067e-9718-4879-85f9-da5ecc0a6eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>714d005b-b667-4f02-8e37-3b548b83a50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[11]</value>
      <webElementGuid>e7ad1f18-ac18-432d-a712-32b930d1f821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/ul/li/a</value>
      <webElementGuid>465bb3ad-6597-4868-b4d4-893776790e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Ubah ' or . = 'Ubah ')]</value>
      <webElementGuid>8019f108-36fd-4d18-8105-b4788365ea67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
