<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Opsi</name>
   <tag></tag>
   <elementGuidId>38f45e29-5c70-4f16-84e3-f997192151db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7885da36-d6ce-44db-a3a9-c580ff8a1e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e237787f-469c-44c0-80e7-2d20750ebb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green btn-sm btn-outline btn-circle dropdown-toggle </value>
      <webElementGuid>e230b17b-374d-4406-af6c-f4ef25a43692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>e7180d54-ff72-482b-805d-fc5d3c3b4f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                 Opsi 
                                            </value>
      <webElementGuid>ea963fff-85d0-4160-9f6d-c08de15619ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dv_HeaderContainer&quot;)/div[@class=&quot;table-primary&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/table[1]/tbody[1]/tr[1]/td[2]/div[@class=&quot;page-toolbar&quot;]/div[@class=&quot;btn-group pull-right&quot;]/div[@class=&quot;actions&quot;]/button[@class=&quot;btn green btn-sm btn-outline btn-circle dropdown-toggle&quot;]</value>
      <webElementGuid>0283184f-9c3e-45d0-b2c6-6a472396ba75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>7091f195-6f98-438b-8aae-309f9303c58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_HeaderContainer']/div/div/div[2]/table/tbody/tr/td[2]/div/div/div/button</value>
      <webElementGuid>7d15431b-5f7b-47b8-9862-76cd829776dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Baru'])[2]/following::button[1]</value>
      <webElementGuid>0f397e99-dd3a-45bd-a3ac-6b7f909d5364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form ini digunakan untuk melakukan penempatan asuransi'])[1]/following::button[1]</value>
      <webElementGuid>0bd4d694-9247-48ad-b86f-9b70ea2defde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Mutakhir'])[1]/preceding::button[1]</value>
      <webElementGuid>9c480a40-48df-4249-ba75-fd3c85348e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penempatan Asuransi'])[2]/preceding::button[1]</value>
      <webElementGuid>321ff9e2-a2a1-48a1-ae9c-69cef297ca77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/button</value>
      <webElementGuid>f156cb25-1b8f-449e-94fa-cc6544b22751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                                 Opsi 
                                            ' or . = '
                                                 Opsi 
                                            ')]</value>
      <webElementGuid>9fd75cab-687f-47c7-a1c3-6217f0307553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
