<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_TambahBaru</name>
   <tag></tag>
   <elementGuidId>4e705996-9d4b-463c-b1e8-84fe217c3deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnGlobalNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnGlobalNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba1be4bf-9d18-4118-bd22-b434da19cfe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>a566801e-c960-4b8a-a20d-89a187845d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green btn-outline btn-circle btn-sm</value>
      <webElementGuid>8908baf3-8f48-410f-9d07-3e404684da9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGlobalNew</value>
      <webElementGuid>15548568-2d12-4a50-b168-9b5e52c66af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Baru
                                                </value>
      <webElementGuid>5b5451a9-7073-4c59-bf4e-517163664d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGlobalNew&quot;)</value>
      <webElementGuid>7fbe9c01-db6b-4073-b409-372f07d94e71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnGlobalNew']</value>
      <webElementGuid>7912cfe5-960f-4c58-aabd-145957cd640c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_HeaderContainer']/div/div/div[2]/table/tbody/tr/td[2]/div/div/div/div/a</value>
      <webElementGuid>2fccf63e-8ab2-4cfc-825e-0ea641d9ac83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Tambah Baru')])[2]</value>
      <webElementGuid>e49d8228-2926-4995-802b-94ba69b28762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form ini digunakan untuk melakukan penempatan asuransi'])[1]/following::a[1]</value>
      <webElementGuid>4d57c2a7-35e0-43db-818a-8c1e57d9e7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Mutakhir'])[1]/preceding::a[1]</value>
      <webElementGuid>9d82e835-791f-438b-b13f-5f5a15bf9198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[7]</value>
      <webElementGuid>70dd6261-e9e6-4065-8874-4a7f71afc601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/a</value>
      <webElementGuid>73d93300-69ef-40e1-a0d9-8e108fc10d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'btnGlobalNew' and (text() = 'Tambah Baru
                                                ' or . = 'Tambah Baru
                                                ')]</value>
      <webElementGuid>6f73d188-194c-4188-9b9f-239d6b225f32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
