<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Jurnal</name>
   <tag></tag>
   <elementGuidId>78043652-e46d-4284-b918-ad51809413ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnJournal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnJournal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46e81cd2-661d-4859-8a18-82fc3d14a721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnJournal</value>
      <webElementGuid>a1390d4b-3e9b-426d-9c32-506f38f6172e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>caf305ea-5f58-4ceb-a3da-19b14990f172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn purple</value>
      <webElementGuid>415b3a4b-ee5a-4592-a8a5-38cb17f823e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jurnal</value>
      <webElementGuid>7aa779ba-8b8a-4e09-a480-d6a75c4cf317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnJournal&quot;)</value>
      <webElementGuid>2f58a9d0-cf16-47a1-9490-6188875c417d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnJournal']</value>
      <webElementGuid>6b8c0e53-7014-4835-85d5-476a5f7ef8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvJournal']/div/div/div/div/button</value>
      <webElementGuid>a04247ae-f324-4e7f-aa67-5ce9f440d092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/following::button[1]</value>
      <webElementGuid>5a895474-8e8f-4a0c-9838-f37734c72263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bersihkan'])[1]/following::button[2]</value>
      <webElementGuid>83357f65-9183-4e72-9e47-eb0ced8c32f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revisi'])[1]/preceding::button[1]</value>
      <webElementGuid>e1c4587a-b53a-440f-8c9f-ed79b85b69d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menolak'])[1]/preceding::button[2]</value>
      <webElementGuid>2b36aa9d-fd1b-45a3-a07f-c302c83f8d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jurnal']/parent::*</value>
      <webElementGuid>84066e92-1769-452f-b3b7-26ab1cbabce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div/button</value>
      <webElementGuid>176e5c16-8a87-4148-b264-34ebbc9568f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnJournal' and (text() = 'Jurnal' or . = 'Jurnal')]</value>
      <webElementGuid>9c691928-5d85-4734-89da-e50e5f80f328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
