<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Installment</name>
   <tag></tag>
   <elementGuidId>076cfa2e-c7e7-401c-926f-c423dc2c13cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnInstallment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnInstallment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1846bffc-10fc-4e10-a359-595a80fd07e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn blue</value>
      <webElementGuid>f3027367-5c4d-4146-a0de-e5dca7755db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnInstallment</value>
      <webElementGuid>e3c24d05-c4d4-40d8-aea5-93f2146512fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Installment</value>
      <webElementGuid>af228994-6936-4020-a608-35f983251407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnInstallment&quot;)</value>
      <webElementGuid>c5c245ea-48e9-459b-a4d4-50b1d1b6c94b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnInstallment']</value>
      <webElementGuid>7c6de85d-bdcc-455f-bad4-93d5896c1c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div[2]/div[13]/div/button</value>
      <webElementGuid>64d80df5-5863-421f-8d19-964f8286d587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::button[1]</value>
      <webElementGuid>79c0f292-d0a1-4aa4-b8d9-41748e4b8dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Stamp Duty &amp; Policy Cost'])[1]/following::button[1]</value>
      <webElementGuid>640a7d4b-a988-419f-9b41-b7eeeee95789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Endorse'])[1]/preceding::button[1]</value>
      <webElementGuid>66edf407-0438-44ce-8ffb-b945a5e84da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detil'])[1]/preceding::button[2]</value>
      <webElementGuid>ad8a5b3b-ac1f-4fc5-b6da-5879f857e1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Installment']/parent::*</value>
      <webElementGuid>6a9e2026-70c3-4952-908d-61a77f118ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/button</value>
      <webElementGuid>8bc1eb3e-2c40-4fcd-a56f-48c47501759a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnInstallment' and (text() = 'Installment' or . = 'Installment')]</value>
      <webElementGuid>fccf3f1f-8abf-4306-8e55-262de9d46088</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
