<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Simpan</name>
   <tag></tag>
   <elementGuidId>34c8daa1-bdba-4e3b-994a-6628f05add75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveGlobal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSaveGlobal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>398fcc63-1882-4b40-81d3-dc0a37e09888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveGlobal</value>
      <webElementGuid>f3bd1291-7c1f-4e80-89e4-a0cffcdf548e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green metro-save btn_save</value>
      <webElementGuid>6cf1dc1e-8829-4e08-883b-0e636e79816a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>1067937e-7c62-42fe-8167-0485b13bffc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>3a8ba40b-c32c-4daa-bba9-3325d3bcaecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveGlobal&quot;)</value>
      <webElementGuid>eeb68382-f554-42ec-8e2b-0cb7a44e1336</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSaveGlobal']</value>
      <webElementGuid>d0c21c57-3bc0-409d-adf3-2b677747e29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div[3]/div[2]/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>2697e11b-29f7-4f23-aaed-ef1444141c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bersihkan'])[1]/following::button[1]</value>
      <webElementGuid>968eba89-3e43-48ab-be30-93bc58b5e986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posting'])[1]/following::button[2]</value>
      <webElementGuid>9797f230-45ac-47ac-bcd5-b6a62d58b491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jurnal'])[1]/preceding::button[1]</value>
      <webElementGuid>82e381d0-07c2-42a0-a0cb-e014a7efecc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revisi'])[1]/preceding::button[2]</value>
      <webElementGuid>9ea4dcfc-bff7-4655-95a2-dc10657d0581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>5382dd04-0dc1-44af-8d51-d894f496bd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>66a50c30-39a7-43d1-bdbf-1c0d408b2d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveGlobal' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>7cf9c6be-475f-489b-a2a5-06332afd8401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
