<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_input_NoTransaksi</name>
   <tag></tag>
   <elementGuidId>0c656a71-7a05-48c4-9310-37c6f147e8c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jqg2_No_Transaksi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jqg2_No_Transaksi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>125017f5-5790-4737-a0f9-52fcf09c99c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eaf4d4c9-ac3c-4005-ad2b-515c075c3c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_No_Transaksi</value>
      <webElementGuid>2d5a2725-240d-43ce-9e02-8246bb2f720a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>No_Transaksi</value>
      <webElementGuid>f3b7d447-3289-4e81-869e-842ee5f43baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>cf9a47e7-7249-4650-beee-b490992c9f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>cb4b8bac-68a1-4409-8355-eb5e3fb1838f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_No_Transaksi&quot;)</value>
      <webElementGuid>94c3e67f-f564-4099-8834-f3e40c4bc6be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg2_No_Transaksi']</value>
      <webElementGuid>55a9433f-2274-4866-b3ac-9b5a162a77f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg2']/td[5]/input</value>
      <webElementGuid>4fe37db9-d3f9-4841-af2d-c277fef49f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>90769ebf-83c1-470b-90f2-1252fc9ddfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg2_No_Transaksi' and @name = 'No_Transaksi']</value>
      <webElementGuid>78455cfb-fbe3-4565-8ae0-edff01c131d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
