<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_input_Nilai</name>
   <tag></tag>
   <elementGuidId>a088c715-8b6c-4363-9073-204febb24794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jqg2_Nilai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jqg2_Nilai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5120b16-f730-48f2-92cd-f700e6a21224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>338f6754-852b-4253-80e8-1a4faaa14e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_Nilai</value>
      <webElementGuid>6687b464-a7d5-4eec-9ddb-38fd2c34f544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nilai</value>
      <webElementGuid>c7a263ef-d5e9-48d7-928b-3f8d2cc0837d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ad7678d7-2b10-41a3-8bad-09301ab3b19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable text-right</value>
      <webElementGuid>d983e2a7-7895-4e6a-b84c-f6bd39e415b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_Nilai&quot;)</value>
      <webElementGuid>b2dcc766-b51a-494e-a032-cfd06852e43a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg2_Nilai']</value>
      <webElementGuid>5b026485-c3c0-48b5-88a1-bce5147a3235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg2']/td[6]/input</value>
      <webElementGuid>b4c2baa2-3a0e-442e-8b51-598cdaf53829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>6eda697a-cdac-4de4-a5ed-089565cb7e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg2_Nilai' and @name = 'Nilai']</value>
      <webElementGuid>18c135d4-c955-44d3-8aa5-88270fda178f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
