<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Detil_input_TglTransaksi</name>
   <tag></tag>
   <elementGuidId>fdb68daf-a30d-4d5a-84ff-c4ca1ca1a765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jqg2_Tgl_Transaksi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jqg2_Tgl_Transaksi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfd25035-2088-48c0-8b95-808255d7a696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82d62d54-94fa-4c81-8a96-d66e44c165a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_Tgl_Transaksi</value>
      <webElementGuid>c3dcd231-49f7-477b-ba59-908d008289b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Tgl_Transaksi</value>
      <webElementGuid>a707d2f6-7ebb-459c-b213-ba4f9726b51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>86792922-39f8-45ee-9dc7-aa3b261b5846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>63c19a40-ccfb-4c93-ac39-738dd148920b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_Tgl_Transaksi&quot;)</value>
      <webElementGuid>3c236013-d4b8-460d-a55e-38197cb9e081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg2_Tgl_Transaksi']</value>
      <webElementGuid>69f4c8f4-a04d-4b90-8ec3-51986bee74f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg2']/td[4]/input</value>
      <webElementGuid>dd0f0b91-9bef-47ee-9eea-9d0405c8fba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>e835ec54-a064-43cd-a6e6-c3b212ae73b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg2_Tgl_Transaksi' and @name = 'Tgl_Transaksi']</value>
      <webElementGuid>52d580b4-c9d1-4567-adec-4d91b415436a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
