<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_NoPolis</name>
   <tag></tag>
   <elementGuidId>dfa14083-65c7-426a-8390-f792f6da3339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_NoPolis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_NoPolis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95a23e63-3018-4f32-b14d-a6e18467aafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd27157b-2d4a-4b0f-9b23-6797cb2c3ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NoPolis</value>
      <webElementGuid>6784c1af-8e97-4750-a834-2936e2fd4e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_NoPolis</value>
      <webElementGuid>76a112e6-d54b-47b1-b7b6-84275ab38699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_NoPolis&quot;)</value>
      <webElementGuid>819eced8-c9e4-43ce-b22d-c387f3b5841f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_NoPolis']</value>
      <webElementGuid>c3139080-3095-42d4-9029-07a777ca191b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[6]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>70c22b4e-e238-48b8-9081-148b61cc0efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>1ee4c59d-9732-49da-b336-931d90c8a2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NoPolis' and @id = 'gs_NoPolis']</value>
      <webElementGuid>4836053c-f2d7-44ba-a5a4-6e4e3da44457</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
