<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_TglTransaksi</name>
   <tag></tag>
   <elementGuidId>6d142830-5a17-4feb-9abe-20605c5cd905</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_TglTransaksi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_TglTransaksi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b0d888f-347a-4c94-934c-77e8239ff5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eedf7ff0-6ca4-4fca-848a-2aa2dc51a402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TglTransaksi</value>
      <webElementGuid>b82a115c-f3ac-4844-9bf8-8410e8380b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_TglTransaksi</value>
      <webElementGuid>be22d3cb-e37d-46ff-96cc-3fd33eb9133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_TglTransaksi&quot;)</value>
      <webElementGuid>b7fdabae-e212-4fd3-a19c-faeedec7ec74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_TglTransaksi']</value>
      <webElementGuid>1cb672c8-00ad-46e5-9f97-8d1e445b1d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ede62bb3-979f-4fdb-863d-578cf9ec88dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>5f804903-a980-4970-a600-f36c45b63566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TglTransaksi' and @id = 'gs_TglTransaksi']</value>
      <webElementGuid>81870cd6-9080-4312-a022-62293a6f0737</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
