<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_NamaProyek</name>
   <tag></tag>
   <elementGuidId>e966311b-c031-4574-b6f2-ddec09cfbef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Nama_Proyek</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Nama_Proyek']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ce9996c-4800-454e-a62d-688360d2691d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5d88158-f7cc-4415-b8bd-172c74527fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nama_Proyek</value>
      <webElementGuid>5a458d7c-55b6-440f-9d85-177430fc9997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Nama_Proyek</value>
      <webElementGuid>76f0463a-fc4b-448d-80ee-03cded395470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Nama_Proyek&quot;)</value>
      <webElementGuid>da4625d7-99b5-411c-93fa-7addd882a05d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Nama_Proyek']</value>
      <webElementGuid>c9df36cf-811a-4b73-aae4-b1aae9143240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>1876034f-2ae5-464a-bb5d-c510f0ded818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>b5f5a9b8-7737-499a-9404-3447e8b10ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Nama_Proyek' and @id = 'gs_Nama_Proyek']</value>
      <webElementGuid>9192b064-f6a9-47ff-94b9-25d2ca6eab19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
