<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_SumInsured</name>
   <tag></tag>
   <elementGuidId>032e1619-ad38-4b9e-85fe-50f570660706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Sum_Insured</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Sum_Insured']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a7fc675-0a6a-4334-aea7-cd5eeaf7bcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27bd3965-0c42-4c59-bc13-8a497590407d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sum_Insured</value>
      <webElementGuid>af82d301-361b-4f0b-990c-0938604d5f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Sum_Insured</value>
      <webElementGuid>3b1fcb5c-1ff4-4afa-ae3a-413a171e3664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Sum_Insured&quot;)</value>
      <webElementGuid>3450b342-c88a-49c7-b57c-21b08a804e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Sum_Insured']</value>
      <webElementGuid>7004dc20-e532-496f-a31a-cdce1b0686d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[7]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e5ac410b-37d9-4d03-afa0-185b74b264b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>3fc233ff-4be1-47f4-9cef-5892042c1b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Sum_Insured' and @id = 'gs_Sum_Insured']</value>
      <webElementGuid>3074e988-4f2a-4e07-b14e-4fc99cc9b027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
