<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_select_StatusPersetujuan</name>
   <tag></tag>
   <elementGuidId>57f15a88-575b-4ea4-963f-9fc5c1d9030c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Status_Approval_Str</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gs_Status_Approval_Str']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>be1c1808-7cb7-452c-9f2f-8ce37bf1e72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Status_Approval_Str</value>
      <webElementGuid>12e9fb00-2307-4142-bdf4-f06efec35f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Status_Approval_Str</value>
      <webElementGuid>73b0c4fe-2204-4564-ae47-b84415632a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semua Not PostedRequest ApproveWaiting for ApprovalApprovedRejectedClosed</value>
      <webElementGuid>1a914364-a272-42a5-aa8b-15797b209479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Status_Approval_Str&quot;)</value>
      <webElementGuid>3f4c0caa-04af-4ddf-acac-fb72e3a8a529</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gs_Status_Approval_Str']</value>
      <webElementGuid>eb61f809-1b16-482d-a2d0-708e98e1f541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[9]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>d8b143c6-d806-4759-af9d-aeb69481b353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[7]/following::select[1]</value>
      <webElementGuid>f089c141-730d-49b6-bf54-ce905e95429b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[6]/following::select[1]</value>
      <webElementGuid>32204f78-2a64-43e8-b43e-5a2d36e1d66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[8]/preceding::select[1]</value>
      <webElementGuid>a6efefbb-5a62-4d6b-b2c3-d4ebec458bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[9]/preceding::select[2]</value>
      <webElementGuid>04dfb6f2-8329-448f-90bb-2b6262ec847e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>dab11e4e-f485-4ef7-9e28-ecbce7229b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Status_Approval_Str' and @id = 'gs_Status_Approval_Str' and (text() = 'Semua Not PostedRequest ApproveWaiting for ApprovalApprovedRejectedClosed' or . = 'Semua Not PostedRequest ApproveWaiting for ApprovalApprovedRejectedClosed')]</value>
      <webElementGuid>7563c134-e35e-4d90-8e1b-dcbedac33543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
