<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_KodePenempatanAsuransi</name>
   <tag></tag>
   <elementGuidId>759316d4-867f-4aa3-9f48-ad5ce06b86ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Kode_Transaksi_Desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Kode_Transaksi_Desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54670146-6247-41ac-9e00-216459dbc135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>365d195a-1d48-488b-80fe-1dee12afd1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kode_Transaksi_Desc</value>
      <webElementGuid>8e5dc71d-e9e4-4e5f-afb9-fbd79168faad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Kode_Transaksi_Desc</value>
      <webElementGuid>7567f209-af59-4b51-b718-eb74733ff257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Kode_Transaksi_Desc&quot;)</value>
      <webElementGuid>f4d84fd8-7104-43b2-a14d-84072363becb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Kode_Transaksi_Desc']</value>
      <webElementGuid>2d2902fd-74a9-452e-9ede-c7bd9bea2eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>d39dce87-a2f7-44a2-bd73-9b93c44ca376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>ad3cb15b-2035-47b9-a131-2eee4e4d1b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Kode_Transaksi_Desc' and @id = 'gs_Kode_Transaksi_Desc']</value>
      <webElementGuid>7d5d025e-6962-4e57-85b1-db5f7badf239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
