<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_TipeAsuransi</name>
   <tag></tag>
   <elementGuidId>9aa44b6f-6b48-4f5f-8f7d-026cd38e3859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_TipeAsuransi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_TipeAsuransi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>990858df-c8a7-48d0-bbb9-7672be36228d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61aed40d-9417-4920-94bd-86e5c8b9daa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TipeAsuransi</value>
      <webElementGuid>c05a6bcf-5114-4894-862b-25ff95941c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_TipeAsuransi</value>
      <webElementGuid>680cd7f9-2312-4c9c-baa2-ec3500845f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_TipeAsuransi&quot;)</value>
      <webElementGuid>e250f1d1-ac64-430e-b6b6-d0247434a47e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_TipeAsuransi']</value>
      <webElementGuid>9f6c9e13-d3a0-44d8-a60e-941591b1cb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[5]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a3dd3124-b279-49dc-81bf-1b88ddc0a4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>0025a0d1-4dd2-4de2-8667-906853c33f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TipeAsuransi' and @id = 'gs_TipeAsuransi']</value>
      <webElementGuid>341f756f-3a9b-4452-a1f2-f61b41ed3aa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
