<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Premium</name>
   <tag></tag>
   <elementGuidId>cb433388-8bcf-4bd9-8da1-600832197c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Premium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Premium']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4f26409-3133-4b05-bcd1-df011408925f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9884753f-ace8-4bd4-94f4-e22e02bf883d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Premium</value>
      <webElementGuid>5df508d9-4557-430d-b9cb-c4cf124d76c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Premium</value>
      <webElementGuid>375f8797-0377-4375-ab15-851546c99c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Premium&quot;)</value>
      <webElementGuid>7fa4e086-ce55-413d-b99c-5b41baed86df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Premium']</value>
      <webElementGuid>0d7181f2-65f7-46ae-b321-5b9e17ae32ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[8]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ad921674-48d4-4e21-80ea-e42d3803765b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[8]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>8f12a4b4-c6ef-4bea-89ad-8ed8b4962ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Premium' and @id = 'gs_Premium']</value>
      <webElementGuid>07bab8dc-a848-47ee-8b9e-788b90252782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
