<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_select_Status</name>
   <tag></tag>
   <elementGuidId>66d4a715-cb70-49e1-b40a-b3c7e32a4aa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs_Status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gs_Status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e987abc3-a471-4279-b798-05bfb86a68b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>de37b1d2-d76b-4e4a-95df-3958ba322aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Status</value>
      <webElementGuid>d7975a3a-343f-4255-b0ac-f2e77bfd106d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALLAktifNon Aktif</value>
      <webElementGuid>5c6c2119-2d6e-4b52-9616-175bc91d33db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Status&quot;)</value>
      <webElementGuid>893b6448-70e7-427b-9a45-f8e09d21182f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gs_Status']</value>
      <webElementGuid>cf9c3132-ffae-448c-bae7-0a91dd32a24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[10]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>083838d2-2f67-4fc7-a52b-d8f854a2983f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[8]/following::select[1]</value>
      <webElementGuid>c67323c6-b596-455e-8f7c-e038e39c3e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[7]/following::select[2]</value>
      <webElementGuid>0fa10274-0110-40fe-9881-404c66b02b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[9]/preceding::select[1]</value>
      <webElementGuid>86bff26d-4907-4fd8-acb5-0fcbe0af7590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[10]/preceding::select[1]</value>
      <webElementGuid>16630696-a230-49c3-9d24-0d635cce3462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[10]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>fffa0777-7dce-4ac6-a89e-cd4106b7ff6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Status' and @id = 'gs_Status' and (text() = 'ALLAktifNon Aktif' or . = 'ALLAktifNon Aktif')]</value>
      <webElementGuid>9cc6b5e1-adfa-4468-b209-2bbafacac3fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
