<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoClosing</name>
   <tag></tag>
   <elementGuidId>c6bac258-4f68-4b09-84e5-10176e7462a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtClosingNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtClosingNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65bbb13d-222b-4209-a811-3594d4146788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8a302e8-29c9-4673-a3a2-792bdb4b1170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtClosingNo</value>
      <webElementGuid>e615426f-2ed3-450f-b8a4-b059b24bd512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uppercase</value>
      <webElementGuid>c51393e7-87ed-4f07-a22c-ba706f6f012e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtClosingNo&quot;)</value>
      <webElementGuid>213b5942-a75f-46c2-8bd0-3e6011d734bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtClosingNo']</value>
      <webElementGuid>7252ef68-d22e-4ee4-a53c-12e35de146fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>395b04fb-8079-44c8-a48b-cacc192f8a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/input</value>
      <webElementGuid>4e8de9fc-1839-467e-8d92-b89e6fcaccf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtClosingNo']</value>
      <webElementGuid>387622b8-98b1-49d1-96ff-013dc7351206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
