<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Premium</name>
   <tag></tag>
   <elementGuidId>af7f64fc-8374-4341-942d-315423da3028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPremium</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPremium']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>557dde50-873f-4b42-85cd-bcdcaa4ac735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>171161f9-4dc1-426d-98dd-c95c2046f654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPremium</value>
      <webElementGuid>b2badd69-74ec-48a4-9f5d-7646c29b8751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uppercase text-right</value>
      <webElementGuid>86befb7a-6b85-4faf-9394-238b7e47ede4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPremium&quot;)</value>
      <webElementGuid>0a619d19-92b0-4b07-9c2e-67dacfdb7d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPremium']</value>
      <webElementGuid>411c35c6-c9d8-4957-a616-f07c636ae017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>d7ccfb7f-3376-4f13-b086-67f35a7508e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>22355f1e-3baf-44ac-9f13-b64d799801c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPremium']</value>
      <webElementGuid>20710a17-40aa-4f00-8e01-97331458d339</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
