<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeriodeAkhir</name>
   <tag></tag>
   <elementGuidId>fb2329e3-08da-4063-9a2a-9c43f9f45b47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPeriodeAkhir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPeriodeAkhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93e5771c-bda4-4551-962e-7d2be6bf9615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c06e837e-a772-4fb6-9072-e501f34e654a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2aedc3d0-7bb5-455b-af8c-cbcdd55f61e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPeriodeAkhir</value>
      <webElementGuid>1d87050a-cc13-41b4-91c8-591637aa254a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPeriodeAkhir</value>
      <webElementGuid>5748f508-ec0f-4e97-83f7-184db2b5337c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPeriodeAkhir&quot;)</value>
      <webElementGuid>c0705d08-941b-470c-9c28-ccc96f83448a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPeriodeAkhir']</value>
      <webElementGuid>7e0a9a21-45d7-4cea-85ce-fdec13a04858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div/div[8]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>4601f02b-b660-457d-9929-5771d9497e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div[2]/div/input</value>
      <webElementGuid>f53c2ed5-6f09-4fac-82f9-8c0b21e24d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPeriodeAkhir' and @name = 'txtPeriodeAkhir']</value>
      <webElementGuid>4ad120ab-05b3-4209-9961-a9c5d0531c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
