<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoPolis</name>
   <tag></tag>
   <elementGuidId>6613896f-50f8-4058-bec1-ac0eb60b4289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNoPolis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNoPolis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3ed13d9-1cef-484d-a271-027fe509b7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cee2e392-249a-468f-9a3b-b607264ee9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNoPolis</value>
      <webElementGuid>379c67e0-c599-46a4-8715-8f0e830524c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uppercase</value>
      <webElementGuid>0090ce59-1075-488f-8aa8-dd15493dbd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNoPolis&quot;)</value>
      <webElementGuid>8c42a49e-501d-41d0-bb93-d02e1ef747c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNoPolis']</value>
      <webElementGuid>8d535034-7f96-4d61-8f84-2d3444959d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div/div[7]/div/input</value>
      <webElementGuid>36b67fa2-d3e4-4056-a3c8-7f0d8a8c42fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>63a5ec0d-6c30-4796-bd99-a86504e23589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtNoPolis']</value>
      <webElementGuid>81fce209-8366-4c95-864c-b1f3bd537324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
