<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeriodeAwal</name>
   <tag></tag>
   <elementGuidId>dc370970-733e-4e3c-bdd0-0af0fe1686cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPeriodeAwal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPeriodeAwal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0717635d-0f44-4097-9d63-8b12e42b44d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af3eac7a-c8f4-4aca-a839-ab7650ff7c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a4aa870c-812c-427f-b45b-8510732201f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPeriodeAwal</value>
      <webElementGuid>0dfc5af8-c96b-4369-8d9c-60d8d6732b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPeriodeAwal</value>
      <webElementGuid>63cd3c01-c23a-4f61-8d6a-5cb414fe0c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPeriodeAwal&quot;)</value>
      <webElementGuid>700014e6-3b95-4cf9-be96-4f7d218f801d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPeriodeAwal']</value>
      <webElementGuid>22da74da-66ef-4a97-9bf0-da87c224ddd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div/div[8]/div/div/div[2]/div/input</value>
      <webElementGuid>edebf17d-721a-4d28-b925-d5254b675144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/input</value>
      <webElementGuid>c3c7e0d1-647c-433a-b59c-73b95cec3503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtPeriodeAwal' and @name = 'txtPeriodeAwal']</value>
      <webElementGuid>7344775e-fcc4-4d9a-94da-be0f584a9cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
