<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SumInsured</name>
   <tag></tag>
   <elementGuidId>5284a201-2462-4e56-9613-c5e9fcb2d4ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSumInsured</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSumInsured']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13a36a65-70d7-4172-86b9-a6bd5a4dab40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d12c2bbb-009f-43a8-b712-425faa8b3d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSumInsured</value>
      <webElementGuid>a27ab49e-c89f-48d5-bd35-fb50683fbb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-right</value>
      <webElementGuid>228df65d-8ba6-4a1f-8806-dea8da3e5ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSumInsured&quot;)</value>
      <webElementGuid>c4377577-9310-4adb-9b77-99561f2d452e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSumInsured']</value>
      <webElementGuid>02883062-d8de-4748-8c49-0d99c0106ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>007b9eef-91a4-4b49-8ba9-aaed17fb209b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>0297a38f-6bbe-4e67-84ea-915bf907c814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtSumInsured']</value>
      <webElementGuid>8f17a938-ea93-4477-b066-9922cb533efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
