<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan</name>
   <tag></tag>
   <elementGuidId>78a53137-baa8-44e3-a24d-90e87a2bd400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtKeterangan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtKeterangan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a0cf6566-7dac-4ce4-a8a0-a5ee91a9dad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtKeterangan</value>
      <webElementGuid>e0a8e71a-bc87-4923-b4bf-9e8517ae13cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uppercase</value>
      <webElementGuid>581a7cf0-c9a9-4244-a263-bf21f25b6ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a8b82e76-03b7-4963-af3a-6529e9a52616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Keterangan</value>
      <webElementGuid>e76faa7e-1c5c-4e9c-b8d3-0dd85f4b4e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtKeterangan&quot;)</value>
      <webElementGuid>a66c5d5e-e943-485a-8347-7e42e41d6994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtKeterangan']</value>
      <webElementGuid>d7b570c7-1f63-4aad-afb9-f32f044b7774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div[2]/div[6]/div/textarea</value>
      <webElementGuid>3429e840-b69c-4748-bfdf-8b701c7ae590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>068e114a-332e-45ff-bb48-5120e5514a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'txtKeterangan' and @placeholder = 'Masukkan Keterangan']</value>
      <webElementGuid>447a7994-8b8f-41fd-9c9c-b528056335ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
