<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KursStdRate</name>
   <tag></tag>
   <elementGuidId>3a650bd3-b438-4302-ba14-f5cc25d841cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtStdRate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtStdRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78eca0a3-564c-4759-b9ad-f6b61e69e568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee596c3c-458c-4f21-8cf5-63291b7f4311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-right</value>
      <webElementGuid>19680fb6-1491-40e5-a541-69b0d4733008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtStdRate</value>
      <webElementGuid>50024963-3967-4147-8e7e-2ee31fc30afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtStdRate</value>
      <webElementGuid>c09837af-64b8-433b-b9fd-fb1887874f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtStdRate&quot;)</value>
      <webElementGuid>6663e90e-dcf9-4a28-bb3d-ff8cee260adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtStdRate']</value>
      <webElementGuid>d2cbdb0b-4a1d-4efb-8fed-0abfd16d7429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_DetailContainer']/div/div/div/div[2]/div/div/div/div/div[9]/div/div[2]/div[2]/input</value>
      <webElementGuid>ad53edbd-d040-4bd9-8be4-a88312ddb618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>89465370-eefa-4f66-acd3-5de66760f7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtStdRate' and @name = 'txtStdRate']</value>
      <webElementGuid>a1f927c7-5f11-4897-b04f-2e80f34d69eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
