<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pencarian Mutakhir</name>
   <tag></tag>
   <elementGuidId>ff3c12fa-b041-4957-b64a-21ea981c430c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.advSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dv_HeaderContainer']/div/div/div[2]/table/tbody/tr/td[2]/div/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce372ac9-64df-46c6-a1e9-34f6b6b1a0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>advSearch</value>
      <webElementGuid>fc1cf050-796c-40ad-acad-d95b79e25d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>1c397704-1c5c-47a1-bf3c-5265e3e8e641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pencarian Mutakhir
                                                    </value>
      <webElementGuid>f662a6a6-26c3-47c1-86c9-594fc74e6a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dv_HeaderContainer&quot;)/div[@class=&quot;table-primary&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12&quot;]/table[1]/tbody[1]/tr[1]/td[2]/div[@class=&quot;page-toolbar&quot;]/div[@class=&quot;btn-group pull-right&quot;]/div[@class=&quot;actions open&quot;]/ul[@class=&quot;dropdown-menu pull-right&quot;]/li[1]/a[@class=&quot;advSearch&quot;]</value>
      <webElementGuid>d8d7520f-94e3-40c0-80b5-c3e54ccc561d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dv_HeaderContainer']/div/div/div[2]/table/tbody/tr/td[2]/div/div/div/ul/li/a</value>
      <webElementGuid>e3318762-34fd-4413-b4d6-23ddfd519cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pencarian Mutakhir')]</value>
      <webElementGuid>85a02a81-b19f-4f30-957b-9a62f26eaecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Baru'])[2]/following::a[1]</value>
      <webElementGuid>112594c5-b532-45b7-8c26-f3afae6640c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penempatan Asuransi'])[2]/preceding::a[1]</value>
      <webElementGuid>bb75fe76-2278-4a0c-86f7-831cf2f8d15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pencarian Mutakhir']/parent::*</value>
      <webElementGuid>ebfcc754-16cb-4c78-b18d-bfbb94151d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[8]</value>
      <webElementGuid>e938abd2-cdd1-48e4-a0da-e6b385fc96ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/ul/li/a</value>
      <webElementGuid>04b498f7-6084-4aa6-ab0f-40a3ca0ba8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Pencarian Mutakhir
                                                    ' or . = 'Pencarian Mutakhir
                                                    ')]</value>
      <webElementGuid>761d1712-cef9-4b5d-8112-0c37ff009588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
