<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Installment_input_InstallmentNo</name>
   <tag></tag>
   <elementGuidId>18f937e8-dc9f-470b-b583-1c47fb24deb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@class='ui-widget-content jqgrow ui-row-ltr ui-priority-secondary jqgrid-new-row ui-state-highlight']//input[@name='InstallmentNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg1_InstallmentNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a2c6a59-9d67-4c51-849d-dadb51520f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0851b50-2d9c-4926-8e99-0cb04d6e249b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg1_InstallmentNo</value>
      <webElementGuid>4b25a0ae-25dd-4329-b303-c55066eed49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InstallmentNo</value>
      <webElementGuid>a3289992-ac59-4010-a42e-ea90f09dd719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>fd88a43b-f00f-4512-a355-c54c70d69655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>d9d4d56c-6ecb-45fc-8582-002de2ec1590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg1_InstallmentNo&quot;)</value>
      <webElementGuid>c233daea-2210-437c-aa3b-3315ac6c51a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg1_InstallmentNo']</value>
      <webElementGuid>6fdc88e0-5bbd-4c47-8fab-40f0756f78bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg1']/td[6]/input</value>
      <webElementGuid>c8572351-1c62-4c5c-b0b8-67d7c41d3dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>c482ec15-90d4-4882-acdc-72f52149046b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg1_InstallmentNo' and @name = 'InstallmentNo']</value>
      <webElementGuid>ce233130-1803-4646-807a-25b8cec875a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
