<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Installment_input_ORNo</name>
   <tag></tag>
   <elementGuidId>3eeaeab0-9cef-4d25-a986-b92172b02c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@class='ui-widget-content jqgrow ui-row-ltr ui-priority-secondary jqgrid-new-row ui-state-highlight']//input[@name='OR_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg1_OR_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a08b92b-eb2f-40cd-a506-490e275f8026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5ace4ce-6819-4172-ada9-41559e485615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg1_OR_No</value>
      <webElementGuid>bf91b3ba-225a-4d61-92a3-04c5d8fd2c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OR_No</value>
      <webElementGuid>bb12242c-60ba-477a-8d2d-414d334214b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>fdb9e5e9-6c6a-4d87-a2f9-6dff16e07a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>19ab3547-a982-49f4-aceb-48387871ef27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg1_OR_No&quot;)</value>
      <webElementGuid>e30d249d-a93f-408a-a70e-ed927bf19a1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg1_OR_No']</value>
      <webElementGuid>4c601b57-6942-4e45-976f-a796f480d8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg1']/td[3]/input</value>
      <webElementGuid>da623ffc-c12d-4822-873b-8090682f07e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>9e549582-7dea-4ae9-8be6-15333585829f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg1_OR_No' and @name = 'OR_No']</value>
      <webElementGuid>8d415087-3cc3-4f02-b515-5c44564ce78c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
