<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_PencarianMutakhir_PilihParameterItem</name>
   <tag></tag>
   <elementGuidId>ca787ac6-e40c-4307-aa37-2157ae20c7b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1_slcSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='1_slcSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9b1e1d5c-38cb-44dc-a8aa-7f82f91209ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slcSearch</value>
      <webElementGuid>5837ceb9-8517-446c-b8cf-6fc955e5f05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_slcSearch</value>
      <webElementGuid>147f87f8-03c0-4f3d-b7c7-fd91554d0859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control searchkey</value>
      <webElementGuid>15bf38ae-3082-4608-bee0-9b3cacf6e3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih --Nama ProyekTanggal TransaksiBrokerInsurerPeriode DariPeriode SampaiMata UangTipe AsuransiNo PolisSum InsuredPremiumNo ClosingCatatanNo ORNo Debit NoteTgl Debit NoteNo InstallmentTgl InstallmentNilai InstallmentPotonganStamp Duty &amp; Policy CostTanggal Transaksi DetilNo Transaksi DetilNilai Transaksi Detil</value>
      <webElementGuid>7f79d017-8766-4f60-b378-bdca855b91e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_slcSearch&quot;)</value>
      <webElementGuid>5110d106-6e97-4919-b1ab-eed466431495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='1_slcSearch']</value>
      <webElementGuid>8af743ed-6964-4ceb-ba2f-d7a39aed8d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1_rid']/div/div/select</value>
      <webElementGuid>73f4c99c-761b-44e0-8984-18fb8ae402c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Mutakhir'])[2]/following::select[1]</value>
      <webElementGuid>514733e6-f91a-4ffa-8f84-d9231a00c408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '1_slcSearch', '&quot;', ')')])[1]/following::select[1]</value>
      <webElementGuid>91ef9fb0-efe9-4d45-ad38-a8abb28ce222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::select[2]</value>
      <webElementGuid>126f315f-b5ab-43d2-98c7-aaa16578f093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bersihkan'])[2]/preceding::select[2]</value>
      <webElementGuid>ee0a8431-b517-47f8-acda-01e4728d0980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div/div/div/div/select</value>
      <webElementGuid>d2d2fffd-52b9-4dc5-a0ca-01b031a74fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'slcSearch' and @id = '1_slcSearch' and (text() = '-- Pilih --Nama ProyekTanggal TransaksiBrokerInsurerPeriode DariPeriode SampaiMata UangTipe AsuransiNo PolisSum InsuredPremiumNo ClosingCatatanNo ORNo Debit NoteTgl Debit NoteNo InstallmentTgl InstallmentNilai InstallmentPotonganStamp Duty &amp; Policy CostTanggal Transaksi DetilNo Transaksi DetilNilai Transaksi Detil' or . = '-- Pilih --Nama ProyekTanggal TransaksiBrokerInsurerPeriode DariPeriode SampaiMata UangTipe AsuransiNo PolisSum InsuredPremiumNo ClosingCatatanNo ORNo Debit NoteTgl Debit NoteNo InstallmentTgl InstallmentNilai InstallmentPotonganStamp Duty &amp; Policy CostTanggal Transaksi DetilNo Transaksi DetilNilai Transaksi Detil')]</value>
      <webElementGuid>797e9c40-2d7e-406d-be0c-37fa7323d508</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
