<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Installment_input_StampDutyPolicyCost</name>
   <tag></tag>
   <elementGuidId>dad76bc9-9b4a-44c3-b4ca-0dd88418ea28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@class='ui-widget-content jqgrow ui-row-ltr ui-priority-secondary jqgrid-new-row ui-state-highlight']//input[@name='StampDutyPolicyCost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg1_StampDutyPolicyCost</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88e5ed5e-177c-4f7f-93e2-d791b13fae17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f9087af-ef61-4141-9f7f-df26472af820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg1_StampDutyPolicyCost</value>
      <webElementGuid>d6136e24-7bb7-4a27-af7a-2a4da62756c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StampDutyPolicyCost</value>
      <webElementGuid>245cf2e0-2849-40db-9337-c7db9065b0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4f7363df-6f5b-418c-8a47-9f62bcc81b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable text-right</value>
      <webElementGuid>53488a4e-1df4-413c-8335-7807eaa02b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg1_StampDutyPolicyCost&quot;)</value>
      <webElementGuid>b2db560f-890e-42c7-a1aa-9cef4249d1d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg1_StampDutyPolicyCost']</value>
      <webElementGuid>f91b2571-2791-465a-b097-1d5f33beb12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg1']/td[10]/input</value>
      <webElementGuid>d7670f6b-b0e1-42e7-86a0-f56c64d3af73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/input</value>
      <webElementGuid>7e9bea2c-68d3-446d-8a4c-986931100a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg1_StampDutyPolicyCost' and @name = 'StampDutyPolicyCost']</value>
      <webElementGuid>8ddefb33-d34e-4c12-af55-6af022a475e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
