<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Upload_ButtonUpload</name>
   <tag></tag>
   <elementGuidId>e72be9ec-b6e7-462f-96a2-b0ea69241183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnUpload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnUpload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5730923c-bc57-4da7-9c45-64bf36085c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn blue</value>
      <webElementGuid>38e4e6f4-032b-4f8c-b248-43031a9e1a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnUpload</value>
      <webElementGuid>6646f98a-a3fd-430c-914e-9023e7d171a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>22c8fbf8-3f17-42a6-8c41-18d119ea1e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUpload&quot;)</value>
      <webElementGuid>a349e9f0-050c-4940-be4b-a62c1e41dfdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnUpload']</value>
      <webElementGuid>b7c27f89-d258-41b5-b407-1e332f52d963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dvPopupDocument']/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>5947ba93-edfb-4110-b722-55e13db09d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Dokumen'])[1]/following::button[1]</value>
      <webElementGuid>5e1956d5-558c-423f-b38c-f20e79d975b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menyetujui'])[1]/following::button[2]</value>
      <webElementGuid>bb5d1bf0-c226-4c1f-bed7-7ab72c9feb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installment'])[2]/preceding::button[2]</value>
      <webElementGuid>e4a0800a-04f3-41a0-8227-085d6015734e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[2]/preceding::button[2]</value>
      <webElementGuid>1893a869-bfd7-4abf-a95e-b7e3494c8bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload']/parent::*</value>
      <webElementGuid>25062039-fc29-4b3d-b79e-cbcad01e395c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>da0182f0-1b3d-4cf9-81b4-9592f903d99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnUpload' and (text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>53a178a1-f510-411f-8ad2-70c0549b1501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
