<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Installment_input_NilaiInstallment</name>
   <tag></tag>
   <elementGuidId>663d35cb-2ad5-4fd4-b98c-46f4b496bcc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@class='ui-widget-content jqgrow ui-row-ltr ui-priority-secondary jqgrid-new-row ui-state-highlight']//input[@name='NilaiInstallment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg1_NilaiInstallment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f18cb2a-d50d-46bb-8e86-ac3fc500945b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdc114b2-27c2-4ce6-bcba-1d17b9b395bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg1_NilaiInstallment</value>
      <webElementGuid>2e6f2925-3e83-4601-a5ad-0f4e36d0b177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NilaiInstallment</value>
      <webElementGuid>dbcdcb74-0e67-461a-8db2-4221fd10e357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>881cf293-910c-44ed-91e9-3270453ecb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable text-right</value>
      <webElementGuid>24bdcde1-e438-484e-b284-80062836ea2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg1_NilaiInstallment&quot;)</value>
      <webElementGuid>76f2b852-0e26-4133-9f49-36efebd587f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg1_NilaiInstallment']</value>
      <webElementGuid>595656df-d9c5-447a-bb22-8ef205027cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg1']/td[8]/input</value>
      <webElementGuid>baf2773b-21f8-4536-bef0-ddab2305edc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>d727055e-e835-497c-9e54-868018c2056b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg1_NilaiInstallment' and @name = 'NilaiInstallment']</value>
      <webElementGuid>e2997819-1028-41a1-b44a-ced48153c421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
