<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_PencarianMutakhir_PilihKondisiParameter</name>
   <tag></tag>
   <elementGuidId>60e0caf6-7997-4368-8844-f830b7612658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1_slcOperator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='1_slcOperator']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87357033-948d-434b-bf66-2987214cbd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slcOperator</value>
      <webElementGuid>08ca717a-ec07-4869-b786-f927da72dc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_slcOperator</value>
      <webElementGuid>5b3e1c60-a546-4f13-b56b-36719250db95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectpicker form-control searchOperator</value>
      <webElementGuid>bc4e1bf5-4ea5-4cba-89f4-3c3ab8a9a2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Pilih--isIs NotContainsNot ContainsEqualLess ThanGreater Than</value>
      <webElementGuid>ab23f237-9b51-42fe-92c8-651aee2d3447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_slcOperator&quot;)</value>
      <webElementGuid>8f3a9237-344f-44c8-a771-a261a1eee2e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='1_slcOperator']</value>
      <webElementGuid>398ed544-4c19-41d6-b31b-87e1d6a71def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1_rid']/div/div/select[2]</value>
      <webElementGuid>de5365a6-7510-4dba-9a2a-ab43377e322b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Mutakhir'])[2]/following::select[2]</value>
      <webElementGuid>b1ac9ec9-4cdd-4bd6-828b-a5d908b7fe5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '1_slcOperator', '&quot;', ')')])[1]/following::select[2]</value>
      <webElementGuid>10bb00e5-8afb-4966-bf4c-88a3324c5da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::select[1]</value>
      <webElementGuid>e9abca94-2bd0-4b7d-a4dd-fb7130a7265b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bersihkan'])[2]/preceding::select[1]</value>
      <webElementGuid>08053559-9d6f-451c-ae04-7957dadb1840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>ae06273e-474d-4329-ad78-638f7e6261c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'slcOperator' and @id = '1_slcOperator' and (text() = '--Pilih--isIs NotContainsNot ContainsEqualLess ThanGreater Than' or . = '--Pilih--isIs NotContainsNot ContainsEqualLess ThanGreater Than')]</value>
      <webElementGuid>7184db07-a640-40c2-90ae-18aa3ffa7e76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
