<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_PencarianMutakhir_ButtonCari</name>
   <tag></tag>
   <elementGuidId>c21efa0b-76d0-439b-ae81-f9b2d6b3bfcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.btn-label.icon.fa.fa-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSearchGlobal']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21992181-5319-4c02-a3c7-a8c6196a002a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-label icon fa fa-search</value>
      <webElementGuid>2cd1f5ef-daa8-446e-8d34-001b0307932e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSearchGlobal&quot;)/span[@class=&quot;btn-label icon fa fa-search&quot;]</value>
      <webElementGuid>a84f917c-6dfb-43b8-90b6-4ddf9700e653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnSearchGlobal']/span</value>
      <webElementGuid>37927b03-11e2-4389-b637-48ba120ca9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>65571ee6-fea2-44fc-87fe-4ce5ee6b9067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
