<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Installment_ButtonClose</name>
   <tag></tag>
   <elementGuidId>3636f35c-d89c-453e-b0f3-01c846e507ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ModalInstallment > div.modal-dialog.drag.ui-draggable > div.modal-content > div.modal-header.ui-draggable-handle > button.close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0b58f7e-d019-459e-ad2a-47db53a36429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04f92225-d8af-42e7-a5d7-c76801fdddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>ce7e80e1-57f0-444f-acad-121582b77149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3ab19f9a-e241-4e1e-8355-e884d21d743d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>850962a1-1299-407f-acef-fd5fd36e3c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalInstallment&quot;)/div[@class=&quot;modal-dialog drag ui-draggable&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header ui-draggable-handle&quot;]/button[@class=&quot;close&quot;]</value>
      <webElementGuid>cbb8ea9a-27ed-4b9a-bf5d-38628c16c704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>c0e49a2d-33be-4148-bb81-1e9e3204f815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalInstallment']/div/div/div/button</value>
      <webElementGuid>d757c110-60a7-44c2-91d4-dc5ac292ad1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/button</value>
      <webElementGuid>3c754b4b-5f03-43bc-94b5-13515540255d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>3443cba7-417f-4735-83a2-a7c887536f5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
