<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Installment_Button_Save</name>
   <tag></tag>
   <elementGuidId>4096e410-d9c3-430f-b8d1-32136547a402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30168474-51cd-46e5-8d3c-808f206d85c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>f4771902-e463-406e-b35a-937753049d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSet</value>
      <webElementGuid>32cbfb85-ae45-4a1a-bdea-a9ff9e388a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>93d75fb4-da9c-4037-88c5-fe2d8f9a205f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>051259d6-de47-4915-8bea-26b4d2af07c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSet&quot;)</value>
      <webElementGuid>dd88995b-becc-408d-8666-33b5b05d0128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSet']</value>
      <webElementGuid>78694d3d-93de-4183-8989-4667ade4a993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalInstallment']/div/div/div[3]/button</value>
      <webElementGuid>454e942d-4577-4e22-8575-f4313ddf8760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View 1 - 1 of 1'])[1]/following::button[1]</value>
      <webElementGuid>b2d21947-2975-444d-b2b3-8bd7876d69ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jurnal'])[2]/preceding::button[2]</value>
      <webElementGuid>b6fb088f-bf0f-4acd-b08a-418844df5835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doc No'])[1]/preceding::button[2]</value>
      <webElementGuid>17942af3-afe2-4fde-82b4-ad4cdb3ec321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>f950137b-191c-49de-a644-5862c09814d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>1969949b-78af-448b-89e0-c59ec3174983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSet' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>4866e0d0-5ee5-4990-b721-57521c637f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
