<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_PencarianMutakhir_InputParameter</name>
   <tag></tag>
   <elementGuidId>ad95c6f9-db3c-431a-a0de-7bd72ac7a261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1_txtSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1_txtSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f44fb20c-87f5-4c57-a1f6-2cb93155ebd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>154917cf-eaeb-4d5e-ba49-c335d242e0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_txtSearch</value>
      <webElementGuid>3ad5c25e-1a0d-4d82-9b99-e4df3fefa60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iname</name>
      <type>Main</type>
      <value>txtSearch</value>
      <webElementGuid>bb9b50d8-c310-458a-ad26-e7e8160e9e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control searchval</value>
      <webElementGuid>6e35f04a-e24e-4bc0-b1c3-e239fcb040fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for...</value>
      <webElementGuid>7df9f2e1-2bb9-4643-8199-80bae865d430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_txtSearch&quot;)</value>
      <webElementGuid>750975f2-6ce9-40d7-935d-10e51f32b630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1_txtSearch']</value>
      <webElementGuid>95afcbb4-b124-425d-bcc5-2a202b3c964e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1_rid']/div/div/input</value>
      <webElementGuid>6b7b3147-6646-43b6-8fe1-9ab830e724e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>d2865c7d-076b-475c-8edc-964e359bd9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '1_txtSearch' and @placeholder = 'Search for...']</value>
      <webElementGuid>4ad1e493-eb61-4de7-a0c5-73bb80e3e46b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
