<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Installment_input_DebitNoteNo</name>
   <tag></tag>
   <elementGuidId>bbbdaa1c-6cf5-4e8d-bb0d-ee396bbcc6c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@class='ui-widget-content jqgrow ui-row-ltr ui-priority-secondary jqgrid-new-row ui-state-highlight']//input[@name='DebitNote_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jqg1_DebitNote_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b90f1745-ebd3-47af-8e69-9c75824ef661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34b97f3b-e625-4bc7-978d-2928b9e61466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg1_DebitNote_No</value>
      <webElementGuid>8097a3ce-b838-44d9-be38-e2a108be7f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DebitNote_No</value>
      <webElementGuid>48a818e5-211b-409d-9332-6f7dd0c59f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2df0b600-f9d8-43f4-8afa-370827de1ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>56432e89-9b26-40d1-b177-deb453fe76bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg1_DebitNote_No&quot;)</value>
      <webElementGuid>1a0ed7b8-8d9b-4adb-85bf-088da371abec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg1_DebitNote_No']</value>
      <webElementGuid>ad13c0b3-9bb7-4e0e-a1d1-38e60492eea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jqg1']/td[4]/input</value>
      <webElementGuid>0fb440ab-b669-451d-b164-a5d3acd1ddab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>099d4954-8d53-4010-a065-5b9a4ced4475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jqg1_DebitNote_No' and @name = 'DebitNote_No']</value>
      <webElementGuid>1d6979f9-8b75-4263-b609-eea58d59ca9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
