<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action Button</name>
   <tag></tag>
   <elementGuidId>5b8383bd-9c89-42f1-9d28-7f1da18aa351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='1_editIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1_editIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d0db1da1-2d11-4534-9d24-d0d1439ce6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_editIcon</value>
      <webElementGuid>ad8a0e36-16ba-4f21-a22a-a4464996633a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-h</value>
      <webElementGuid>dc2969b5-9dae-4b5b-9c54-c28a218a113f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RowEdit(1);return false;</value>
      <webElementGuid>7fda8aa3-1dd9-4fe1-8426-fb4d85b54095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_editIcon&quot;)</value>
      <webElementGuid>1f2956f2-ba89-4b8a-8a6d-8a466898f900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='1_editIcon']</value>
      <webElementGuid>35840a97-5f18-4aa2-8b97-64e5ce5ce24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[5]/i</value>
      <webElementGuid>272f92ae-3fe2-42bb-ac49-c35ea0394bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/i</value>
      <webElementGuid>e0e1a66e-a211-4bba-b22d-bea5e2626e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = '1_editIcon']</value>
      <webElementGuid>7a8aac29-7d59-4472-a320-4a660aec6f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
