<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Simpan</name>
   <tag></tag>
   <elementGuidId>282297bc-4d30-471f-a8d1-fc778e0bf425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnSaveGlobal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSaveGlobal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0d2dbe1-6b9a-4031-8bdd-7c6921a5568a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveGlobal</value>
      <webElementGuid>88bc4069-e903-460f-8735-d635a1e3774b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-circle btn-sm btn-primary</value>
      <webElementGuid>3425232b-e258-404d-a417-d9d69e5db94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>46eb47f4-605c-4e6c-8ad0-7f97178d5f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>3ab262e5-251f-4f62-b524-9c62ff59289c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>f4fd730d-03e8-4068-b09a-f6b2524cacbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Save all data</value>
      <webElementGuid>5b0a53e1-2dc0-4d19-aece-83c1032ae7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Simpan
                    </value>
      <webElementGuid>19233287-1f40-4c5c-930e-fef5e03482cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveGlobal&quot;)</value>
      <webElementGuid>33b972dd-da5b-4b06-b231-e7f351aea2ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnSaveGlobal']</value>
      <webElementGuid>c70e43c1-5088-491f-851d-1e630e4e1843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MenuBar']/ul/div[2]/a[3]</value>
      <webElementGuid>87083883-6a5b-47c5-bec6-41f2a4bdabb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save all data'])[1]/preceding::a[1]</value>
      <webElementGuid>fe8f650d-a086-4273-8fc9-b7269aff22a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pelanggan'])[1]/preceding::a[1]</value>
      <webElementGuid>598c1ba7-ca3a-4ff0-8f7f-1593b5c06076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[606]</value>
      <webElementGuid>9089e2f1-9bba-4077-8566-22b675ecb604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div[2]/a[3]</value>
      <webElementGuid>50b254f9-c0e4-4433-aadc-04b48ec564bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnSaveGlobal' and (text() = '
                         Simpan
                    ' or . = '
                         Simpan
                    ')]</value>
      <webElementGuid>45004893-e5e6-40f9-8cb5-0cf16a8b1746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
