<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Group_Customer</name>
   <tag></tag>
   <elementGuidId>8ab81a48-5e1c-47ce-b9f4-ca7623f4a5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Customer_Group_Deskripsi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_Customer_Group_Deskripsi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9f702c8-ffe3-4c17-8ec7-50540d46ce7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1c5beba-efe4-4014-b78d-fe853b70fe91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Customer_Group_Deskripsi</value>
      <webElementGuid>55da12f1-6c7a-4846-ad6d-adff980314a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Customer_Group_Deskripsi</value>
      <webElementGuid>1578ccf3-d307-4d77-94dd-3cfada7ab055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Customer_Group_Deskripsi&quot;)</value>
      <webElementGuid>6ac1cdf2-50a2-424b-8301-3becf40ac1de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Customer_Group_Deskripsi']</value>
      <webElementGuid>102e6ec4-d823-4e0b-9f7b-4c4402dd9673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e34b2c0e-f476-49b5-aa0e-37d9b815fd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>cb7782de-b8c0-418b-b7cd-28f44ab81aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Customer_Group_Deskripsi' and @id = 'gs_Customer_Group_Deskripsi']</value>
      <webElementGuid>c32cacb6-3a2a-4e51-a2cc-58b41722e23f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
