<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Nama_Customer</name>
   <tag></tag>
   <elementGuidId>8a8da3ed-dbb6-4d5e-a841-cdc360ab9deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Nama_Customer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_Nama_Customer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1e860ce-f51b-4bb6-935c-6a3c188316fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a87b29a-1896-4c3a-84d2-d58de9cc1bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nama_Customer</value>
      <webElementGuid>5304ebba-4d3f-411d-8f6c-f6a83bb3ff3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Nama_Customer</value>
      <webElementGuid>e4c038fa-d313-42d3-99af-b28b05359b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Nama_Customer&quot;)</value>
      <webElementGuid>b0f8cd00-e3a2-499e-8806-0c5901043fe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Nama_Customer']</value>
      <webElementGuid>45b7ee83-8670-42b3-8ad4-10bfdc778c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>9020e326-e968-4542-a4cb-1c3083c83f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ca07c1b2-04c8-4d0c-b720-34c530a94117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Nama_Customer' and @id = 'gs_Nama_Customer']</value>
      <webElementGuid>96d7048a-5420-48f3-a81f-17259b01782e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
