<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filter_input_Kode_Customer</name>
   <tag></tag>
   <elementGuidId>f4f724cd-4ae2-4da5-959d-fe9ef6b6f9a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs_Kode_Customer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gs_Kode_Customer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c174a81f-2cc9-46f0-aab6-c75ac5aa19c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d9dc93a-fa6e-4d36-874f-cc3c9d5a5228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kode_Customer</value>
      <webElementGuid>96119af1-cd8b-4ab4-97b1-2d9733eda0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs_Kode_Customer</value>
      <webElementGuid>981cac4f-2a36-4520-8bb9-97f6072fc019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs_Kode_Customer&quot;)</value>
      <webElementGuid>2044cba8-d0ff-48f3-bb55-ff6be71e4052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs_Kode_Customer']</value>
      <webElementGuid>49638834-c3f9-4b84-8b45-a6c5dfed3363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_MainGrid']/div[2]/div/table/thead/tr[2]/th[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>134c6a4e-27d3-43e2-9984-469533c95920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>fef47ae6-24b3-4f0c-928c-5e0466993505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Kode_Customer' and @id = 'gs_Kode_Customer']</value>
      <webElementGuid>6bc4b7d5-4fdc-4145-83cd-9fc763b8fbe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
