<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TahunDidirikan</name>
   <tag></tag>
   <elementGuidId>d99f6853-b185-4b29-928f-7de065ac9af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtYearEstablished']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtYearEstablished</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d161b4ad-fce6-4e45-953c-2ad6c678d561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43422e67-0ca2-41eb-94b6-a6f409a62b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>110b0906-2f7f-4f2e-9144-48ccc9dab1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtYearEstablished</value>
      <webElementGuid>e66e57ad-65bf-4122-b1ff-2b1e31d7e220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtYearEstablished&quot;)</value>
      <webElementGuid>af9a099f-a0e1-40cf-976b-9d5d39e6f814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtYearEstablished']</value>
      <webElementGuid>9c8ff89e-fc83-4cf8-8755-329af2b56925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panelDataPerusahaan']/div/div/div[6]/div/div/input</value>
      <webElementGuid>525e56e1-6a56-431b-abe0-7ff7ccb66b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>d36dce17-2a6a-4632-a7ec-a13265b3192e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtYearEstablished']</value>
      <webElementGuid>b2bf63e7-7d9d-4679-ad95-9983b260013c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
