<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Volume</name>
   <tag></tag>
   <elementGuidId>4aab8bea-a51d-4553-ab21-18ad17be1ce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='panel form-horizontal']//div[@class='col-sm-6']/input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.form-horizontal.panel .col-sm-6 > [type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a17cd861-8b1f-455b-ac27-59ab4b06d16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqg2_Vol</value>
      <webElementGuid>cc7737b3-915c-4c66-bbfb-bd9da03b688d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>5c70f1b0-66c3-4f7b-9b35-2871a0051d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f5234191-f6ae-4e2f-a875-da1cd639ad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60c6e079-47cf-4b16-8006-63e7ac834365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqg2_Vol&quot;)</value>
      <webElementGuid>1392ff68-c32d-4a13-9aa8-3dd022de8bcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jqg2_Vol']</value>
      <webElementGuid>ef8d8224-5b77-4478-89ab-1c28e68e9422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainGridDetail_jqg2']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>7d0692d6-09e8-463e-8e9b-3ff1ef56e65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>72f87d15-4040-4125-a7bc-707eba64c6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jqg2_Vol' and @name = 'name' and @type = 'text']</value>
      <webElementGuid>d32bbe9f-02e2-4178-9ffb-2bd3f08e068c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
